# Generated by Django 2.1.2 on 2018-10-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('s', 'Default Theme'), ('d', 'Dark Theme'), ('c', 'High Contrast Theme')], default='s', max_length=1),
        ),
    ]
